/**
 * English content layer for the EKSPA site. Mirrors lib/content.ts exactly in
 * shape and slugs (slugs are stable across locales so cross-references resolve),
 * with all copy translated to professional English.
 */
import type {
  Solution,
  Product,
  Sector,
  Insight,
  SuccessStory,
  Certification,
  IconName,
} from '@/lib/content'

export const actionModelEn = [
  { key: 'gor', label: 'See', icon: 'eye' as IconName, description: 'Capture the critical signal in cameras, sensors and data.' },
  { key: 'dogrula', label: 'Verify', icon: 'badge-check' as IconName, description: 'Prove identity, documents, transactions and quality.' },
  { key: 'otomatiklestir', label: 'Automate', icon: 'bot' as IconName, description: 'Hand repetitive work to a reliable digital workforce.' },
  { key: 'koru', label: 'Protect', icon: 'lock' as IconName, description: 'Secure data, access and business continuity.' },
  { key: 'donustur', label: 'Transform', icon: 'network' as IconName, description: 'Connect scattered systems into a measurable operating model.' },
] as const

export const deliveryModelEn = [
  { step: '01', title: 'Discovery', description: 'We clarify the goal, current systems, data, risks and success criteria together.' },
  { step: '02', title: 'Architecture', description: 'We design the solution, integration, security and responsibility boundaries.' },
  { step: '03', title: 'PoC', description: 'We run a field validation with defined scope, data, duration and KPIs.' },
  { step: '04', title: 'Rollout', description: 'We manage installation, data migration, training and change management.' },
  { step: '05', title: 'Operation', description: 'We keep the system running with SLAs, support, maintenance, monitoring and continuous improvement.' },
] as const

export const trustBlocksEn = [
  { title: 'Information security and role-based access', description: 'An RBAC approach that ties authority to the job and the job to an audit trail.' },
  { title: 'On-premise and air-gapped', description: 'Architectures that run fully in-house or on closed networks when required.' },
  { title: 'Business continuity and disaster recovery', description: 'Uninterrupted operation through backup, replication and DR.' },
  { title: 'Integration and traceability', description: 'Open APIs, audit trails and end-to-end traceable processes.' },
  { title: 'Nationwide technical support', description: 'Local strength through field teams and a 24/7 support approach.' },
  { title: 'Quality and service management', description: 'Defined processes, SLAs and a measurable service-management discipline.' },
] as const

export const certificationsEn: Certification[] = [
  { code: 'ISO/IEC 27001', title: 'Information Security Management', verified: false },
  { code: 'ISO 9001', title: 'Quality Management', verified: false },
  { code: 'ISO/IEC 20000-1', title: 'Service Management', verified: false },
]

export const solutionsEn: Solution[] = [
  {
    slug: 'dijital-arsiv-ve-kurumsal-bilgi',
    name: 'Digital Archive & Enterprise Knowledge',
    icon: 'archive',
    summary:
      'Turn physical and electronic documents into a secure corporate memory — and, with an AI layer, into sourced knowledge.',
    proofTags: ['OCR', 'Metadata', 'Lifecycle', 'RBAC', 'WORM', 'AI Layer'],
    featured: true,
    detail: {
      problem:
        'Enterprise knowledge stays scattered, unsearchable and unauditable across documents; access is slow and risky.',
      audience: ['CIOs / IT managers', 'Quality and compliance managers', 'Archive and document management teams'],
      whyNow:
        'As document volume grows, manual processes, audit pressure and the risk of knowledge loss grow with it. Scanning without the right archive architecture only produces a digital pile.',
      howItWorks: [
        'Physical and electronic documents are brought into a single managed repository and made searchable with OCR.',
        'Classification and metadata give documents context; RBAC ensures only authorized users have access.',
        'Lifecycle and WORM policies automate retention and disposal rules.',
        'An AI layer accelerates access from document to knowledge with sourced queries.',
      ],
      flow: [
        'Physical / electronic document',
        'Scanning and OCR',
        'Classification and metadata',
        'Authorization and lifecycle',
        'AI-powered sourced query',
        'Business process / RPA action',
      ],
      features: [
        { title: 'OCR and full-text search', description: 'Scanned documents become searchable text.' },
        { title: 'Metadata and classification', description: 'Documents are tagged to the corporate taxonomy.' },
        { title: 'Role-based access (RBAC)', description: 'Access is restricted by job and authority.' },
        { title: 'Lifecycle and WORM', description: 'Retention, versioning and disposal rules are automated.' },
        { title: 'Audit trail', description: 'Every access and change is recorded traceably.' },
        { title: 'AI knowledge layer', description: 'Sourced enterprise question-and-answer.' },
      ],
      integrationSecurity: [
        'On-premise or air-gapped deployment',
        'Enterprise identity provider (LDAP / AD) integration',
        'Connect to business applications via open API',
        'End-to-end audit trail and encryption',
      ],
      useCases: [
        'Large-scale enterprise document management',
        'Centralized document processing across distributed locations',
        'Evidence and retention in audited processes',
      ],
      pocApproach:
        'We start with a PoC scoped to a selected document type and process, with a defined dataset and success criteria.',
      faq: [
        {
          question: 'Can our existing documents be migrated?',
          answer: 'Yes. The existing archive is migrated with a data-migration plan that has a defined scope and validation criteria.',
        },
        {
          question: 'Does it work on a closed network?',
          answer: 'Yes. Fully on-premise and air-gapped scenarios are supported.',
        },
      ],
      relatedProducts: ['dasbase', 'voodoo-rpa'],
      relatedSolutions: ['akilli-surec-otomasyonu', 'bt-altyapisi-ve-siber-guvenlik'],
    },
  },
  {
    slug: 'akilli-surec-otomasyonu',
    name: 'Intelligent Process Automation',
    icon: 'workflow',
    summary:
      'Hand repetitive, rule-based and auditable work to attended or unattended digital workers.',
    proofTags: ['Zero Code', 'Studio', 'Robot', 'Unified Console', 'REST API'],
    detail: {
      problem:
        'Experts spend a large share of their time on repetitive work like copy-paste, data entry and reconciliation.',
      audience: ['COOs / operations managers', 'Finance and reconciliation teams', 'Process excellence offices'],
      whyNow:
        'Repetitive work raises error rates and burnout; as it scales, cost grows linearly. With the right candidate selected, automation delivers a fast return.',
      howItWorks: [
        'Candidate processes are assessed for rules, volume and auditability.',
        'Robots are designed in the studio with low/zero code.',
        'Attended or unattended robots are managed and monitored from a unified console.',
      ],
      flow: ['Candidate process analysis', 'Robot design (Studio)', 'Test and validation', 'Rollout', 'Monitoring and console'],
      features: [
        { title: 'Zero / low-code studio', description: 'Visual flow design for business users.' },
        { title: 'Attended & unattended robots', description: 'Both desktop and server-side automation.' },
        { title: 'Unified console', description: 'Central scheduling and monitoring of robots.' },
        { title: 'REST API', description: 'Programmatic integration with other systems.' },
        { title: 'Audit and logging', description: 'Every step is traceable and reportable.' },
      ],
      integrationSecurity: [
        'Integration with enterprise applications and web interfaces',
        'Secure operation with identity and authorization management',
        'Audit trail and centralized logging',
      ],
      useCases: [
        'Robotic process automation in high-volume operations',
        'Financial reconciliation and reporting',
        'Data transfer between systems',
      ],
      pocApproach: 'We select the first RPA candidate together and demonstrate fast value with a measurable pilot.',
      faq: [
        {
          question: 'Which processes are suitable for automation?',
          answer: 'Rule-based, repetitive, high-volume processes with digital inputs/outputs are the best candidates.',
        },
      ],
      relatedProducts: ['voodoo-rpa'],
      relatedSolutions: ['dijital-arsiv-ve-kurumsal-bilgi'],
    },
  },
  {
    slug: 'video-yonetimi-ve-guvenlik-operasyonlari',
    name: 'Video Management & Security Operations',
    icon: 'video',
    summary:
      'Manage scattered cameras and locations with a federated architecture, map-based alarms and system-health visibility.',
    proofTags: ['Federation', 'Map', 'Alarm Lifecycle', 'Open API', 'High Availability'],
    featured: true,
    detail: {
      problem:
        'As camera count grows, operational visibility drops; alarms lack context and locations are disconnected.',
      audience: ['Security operations managers', 'Critical facility and campus managers', 'IT and infrastructure teams'],
      whyNow:
        'More cameras alone do not bring more security; context-less footage fatigues operators and slows incident response.',
      howItWorks: [
        'Different location and camera infrastructures unite in a federated architecture.',
        'Alarms reach the operator with their location on a map and the relevant footage.',
        'Response is managed with an incident lifecycle and role assignment.',
      ],
      flow: ['Camera / location federation', 'Map-based alarm', 'Relevant footage to operator', 'Incident lifecycle', 'Archive and export'],
      features: [
        { title: 'Federated architecture', description: 'Balance of central control and local autonomy.' },
        { title: 'Map-based alarms', description: 'The alarm’s location is shown on the map.' },
        { title: 'Incident lifecycle', description: 'Incident open, assignment and closure are tracked.' },
        { title: 'System-health monitoring', description: 'Camera and infrastructure status are monitored.' },
        { title: 'Advanced archive and export', description: 'Recording management and evidence export.' },
        { title: 'Open API', description: 'Integration with third-party systems.' },
      ],
      integrationSecurity: [
        'High-availability architecture',
        'Role-based access and audit trail',
        'SOC / PSIM integration via open API',
      ],
      useCases: [
        'Unified video management in critical facilities',
        'Multi-location security and access',
        'Energy and critical-infrastructure visibility',
      ],
      pocApproach: 'We start with a pilot that validates federation and the alarm flow across selected locations.',
      faq: [
        {
          question: 'Can we use our existing cameras?',
          answer: 'The federated architecture aims to unite different camera infrastructures into a single operations layer.',
        },
      ],
      relatedProducts: ['vultureeye'],
      relatedSolutions: ['bt-altyapisi-ve-siber-guvenlik', 'yapay-zeka-ve-goruntu-isleme'],
    },
  },
  {
    slug: 'dijital-kimlik-biyometri-ve-erisim',
    name: 'Digital Identity, Biometrics & Access',
    icon: 'fingerprint',
    summary:
      'Don’t just see identity — verify it with cards, certificates and biometrics, and tie document approval to an audit trail.',
    proofTags: ['eBioKEC', 'eBioSign', 'KimO', 'e-ID', 'NFC', 'T&A'],
    featured: true,
    detail: {
      problem:
        'Seeing identity is not enough; transactions not verified with a card, certificate and biometrics carry audit and compliance risk.',
      audience: ['Telecom and finance operations', 'HR and access management', 'Compliance and audit teams'],
      whyNow:
        'Fraud and unauthorized-access risks are rising; verifying identity and tying approval to an audit trail is becoming mandatory.',
      howItWorks: [
        'Identity is verified with a card (NFC/e-ID), certificate and biometrics.',
        'Document approval is tied to an electronic signature and an audit trail.',
        'Access and time-and-attendance (T&A) processes are secured with biometrics.',
      ],
      flow: ['Identity capture', 'Card / NFC / e-ID verification', 'Biometric verification', 'Electronic signature / approval', 'Audit trail'],
      features: [
        { title: 'eBioKEC', description: 'Biometric identity verification.' },
        { title: 'eBioSign', description: 'Biometric / electronic document signing.' },
        { title: 'KimO', description: 'Identity verification and reading solution.' },
        { title: 'e-ID & NFC', description: 'Electronic ID-card reading.' },
        { title: 'T&A integration', description: 'Time-and-attendance systems.' },
        { title: 'Audit trail', description: 'Every verification and approval is traceable.' },
      ],
      integrationSecurity: [
        'Personal-data-protection-focused design',
        'Integration with enterprise identity and access systems',
        'End-to-end audit trail',
      ],
      useCases: [
        'Identity verification and electronic contracts in telecom',
        'Digital consent in healthcare',
        'Enterprise access and time management',
      ],
      pocApproach: 'We start with a pilot that validates the verification and signing flow end-to-end at one channel or location.',
      faq: [
        {
          question: 'What is the difference between seeing and verifying identity?',
          answer:
            'Seeing merely observes the document; verifying proves the authenticity of identity with card/certificate/biometrics and ties it to an audit trail.',
        },
      ],
      relatedProducts: ['ebiokec'],
      relatedSolutions: ['saglikta-dijital-donusum'],
    },
  },
  {
    slug: 'yapay-zeka-ve-goruntu-isleme',
    name: 'Artificial Intelligence & Computer Vision',
    icon: 'scan-eye',
    summary:
      'Turn camera footage into intelligent sensors that produce counting, quality, anomaly and security decisions.',
    proofTags: ['Vision QA', 'RPQ', 'Edge AI', 'Object Detection', 'Quality Verification'],
    featured: true,
    detail: {
      problem:
        'Camera footage is watched but produces no decisions; counting, quality and anomaly detection are still manual and error-prone.',
      audience: ['Manufacturing and quality managers', 'Logistics and counting operations', 'Security and facility management'],
      whyNow:
        'Manual counting and quality control produce errors and cost as they scale; vision-based AI delivers consistent decisions.',
      howItWorks: [
        'Camera streams are processed at the edge or centrally.',
        'Object detection and classification produce counting/quality decisions.',
        'Anomalies and security events are relayed to operations.',
      ],
      flow: ['Image capture', 'Edge / central processing', 'Object detection', 'Decision (count / quality / anomaly)', 'Notification to operations'],
      features: [
        { title: 'Vision QA', description: 'Image-based quality verification.' },
        { title: 'RPQ', description: 'Counting and control automation.' },
        { title: 'Edge AI', description: 'Low-latency on-site processing.' },
        { title: 'Object detection', description: 'Real-time detection of critical objects.' },
        { title: 'Anomaly detection', description: 'Flagging of unexpected conditions.' },
      ],
      integrationSecurity: [
        'Works with existing camera infrastructure',
        'Integration with VMS and business systems',
        'Privacy-focused processing',
      ],
      useCases: [
        'Image-based quality control in manufacturing',
        'Counting and shipment verification in logistics',
        'Security anomaly detection on premises',
      ],
      pocApproach:
        'We set a measurable target (e.g. counting accuracy) and run a scoped computer-vision PoC.',
      faq: [
        {
          question: 'How is success measured in an image-based counting PoC?',
          answer: 'Accuracy against a reference dataset, false positive/negative rates and operational impact are measured together.',
        },
      ],
      relatedProducts: ['vision-qa'],
      relatedSolutions: ['video-yonetimi-ve-guvenlik-operasyonlari'],
    },
  },
  {
    slug: 'bt-altyapisi-ve-siber-guvenlik',
    name: 'IT Infrastructure & Cyber Security',
    icon: 'shield',
    summary:
      'Unite servers, storage, network, cloud, backup and cyber security into a single business-continuity architecture.',
    proofTags: ['Data Center', 'DR', 'EDR/XDR', 'SIEM', 'WAF', 'Backup'],
    featured: true,
    detail: {
      problem:
        'Infrastructure and security are managed piecemeal; business continuity, visibility and response capability fall short.',
      audience: ['CISOs / security managers', 'IT infrastructure teams', 'Business continuity owners'],
      whyNow:
        'As the threat surface widens, scattered defense is insufficient; an integrated business-continuity architecture is needed.',
      howItWorks: [
        'Servers, storage, network and cloud are designed in a single architecture.',
        'Continuity is secured with backup and disaster recovery.',
        'Detection and response are integrated with EDR/XDR, SIEM and WAF.',
      ],
      flow: ['Assessment', 'Architecture design', 'Deployment', 'Monitoring (SIEM/XDR)', 'Backup & DR'],
      features: [
        { title: 'Data center solutions', description: 'Server, storage and network design.' },
        { title: 'DR', description: 'Disaster recovery center and business continuity.' },
        { title: 'EDR / XDR', description: 'Endpoint and extended detection-and-response.' },
        { title: 'SIEM', description: 'Centralized security event management.' },
        { title: 'WAF', description: 'Web application firewall.' },
        { title: 'Backup', description: 'Enterprise backup and replication.' },
      ],
      integrationSecurity: [
        'On-premise, cloud and hybrid deployment',
        'Enterprise identity and log integration',
        'Audit and compliance reporting',
      ],
      useCases: [
        'Business continuity and disaster recovery',
        'Security visibility across distributed facilities',
        'Central security operations center',
      ],
      pocApproach: 'We start with a pilot validating a continuity and detection scenario for a critical service.',
      faq: [
        {
          question: 'Does it integrate with our existing security products?',
          answer: 'Yes. The SIEM and integration layer aims to unite existing products into a single view.',
        },
      ],
      relatedSolutions: ['video-yonetimi-ve-guvenlik-operasyonlari'],
    },
  },
  {
    slug: 'kurumsal-uygulamalar-ve-entegrasyon',
    name: 'Enterprise Applications & Integration',
    icon: 'layers',
    summary:
      'Connect scattered enterprise applications into a single operating model with an open API and integration layer.',
    proofTags: ['Open API', 'Integration', 'Workflow', 'Identity', 'Audit Trail'],
    detail: {
      problem:
        'Enterprise applications run disconnected; data is duplicated and processes break between systems.',
      audience: ['Enterprise architects', 'IT managers', 'Digital transformation offices'],
      whyNow:
        'Disconnection between systems inflates both operational cost and data inconsistency.',
      howItWorks: [
        'Applications are connected through an open API and integration layer.',
        'Workflows are traced end-to-end across systems.',
        'Identity and authorization are managed from a single point.',
      ],
      flow: ['Inventory and analysis', 'Integration architecture', 'API layer', 'Workflow orchestration', 'Monitoring'],
      features: [
        { title: 'Open API', description: 'Integration through standard interfaces.' },
        { title: 'Workflow orchestration', description: 'Cross-system process management.' },
        { title: 'Identity integration', description: 'Identity and authorization from a single point.' },
        { title: 'Audit trail', description: 'End-to-end traceability.' },
      ],
      integrationSecurity: [
        'Enterprise identity provider integration',
        'Secure API management',
        'Audit and logging',
      ],
      useCases: ['Cross-system data integrity', 'End-to-end process orchestration', 'Legacy system modernization'],
      pocApproach: 'We start with a pilot validating the integration between two critical systems.',
      faq: [
        {
          question: 'Does it work with legacy systems?',
          answer: 'The integration layer aims to unite modern and legacy systems via open API.',
        },
      ],
      relatedSolutions: ['akilli-surec-otomasyonu'],
    },
  },
  {
    slug: 'saglikta-dijital-donusum',
    name: 'Digital Transformation in Healthcare',
    icon: 'heart-pulse',
    summary:
      'Bring digital consent, patient records and paperless processes together with identity verification, archiving and automation.',
    proofTags: ['Digital Consent', 'Patient Record', 'Paperless', 'e-ID', 'Archive'],
    detail: {
      problem:
        'Healthcare processes still rely on paper and manual approval; patient records are scattered and consent and archiving are not auditable.',
      audience: ['Hospital managers', 'Healthcare IT teams', 'Compliance and patient-rights units'],
      whyNow:
        'A paperless hospital is not just scanning; it requires verified consent, accessible records and traceable processes.',
      howItWorks: [
        'Patient identity and consent are verified electronically.',
        'Patient records are managed securely in a digital archive.',
        'Repetitive processes are automated with RPA and integration.',
      ],
      flow: ['Identity verification', 'Digital consent', 'Patient record archive', 'Process automation', 'Audit trail'],
      features: [
        { title: 'Digital consent', description: 'Consent with electronic signature and biometrics.' },
        { title: 'Patient record archive', description: 'Secure and searchable record management.' },
        { title: 'Paperless process', description: 'Digitalization of manual steps.' },
        { title: 'Integration', description: 'Connection with HIS and enterprise systems.' },
        { title: 'Audit trail', description: 'Consent and access traceability.' },
      ],
      integrationSecurity: [
        'Design focused on protecting personal health data',
        'Integration with HIS and identity systems',
        'End-to-end audit trail',
      ],
      useCases: ['Digital consent processes', 'Paperless patient records', 'Process automation in hospitals'],
      pocApproach: 'We start with a pilot validating the digital-consent and archive flow end-to-end in one clinical process.',
      faq: [
        {
          question: 'What does a paperless hospital really mean?',
          answer:
            'Not just scanning documents; it means verifying consent, managing records securely and making the process auditable.',
        },
      ],
      relatedProducts: ['ebiokec', 'dasbase'],
      relatedSolutions: ['dijital-kimlik-biyometri-ve-erisim', 'dijital-arsiv-ve-kurumsal-bilgi'],
    },
  },
]

export const productsEn: Product[] = [
  {
    slug: 'dasbase',
    name: 'DASBase',
    category: 'Digital Archive',
    icon: 'archive',
    tagline: 'A digital archive platform that turns enterprise documents into secure, searchable knowledge.',
    showcase: true,
    problem: 'Documents are scattered, unsearchable and unauditable; access to knowledge is slow.',
    role: 'Moves physical and electronic documents into a single managed corporate memory.',
    proofs: ['OCR and full-text search', 'RBAC and lifecycle', 'AI-assisted sourced query'],
    sectors: ['Public Sector', 'Finance', 'Healthcare'],
    imageAlt: 'DASBase digital archive interface — product screen placeholder',
    detail: {
      problem: 'The corporate document memory is scattered; access is slow, auditing is hard and the risk of knowledge loss is high.',
      audience: ['IT and archive teams', 'Quality and compliance managers', 'Document-intensive operations'],
      whyNow: 'As document volume and audit pressure grow, a manual archive becomes unsustainable.',
      howItWorks: [
        'Documents are scanned, made searchable with OCR and classified with metadata.',
        'RBAC and lifecycle policies manage access and retention.',
        'The AI layer offers sourced enterprise queries.',
      ],
      flow: ['Document intake', 'Scanning & OCR', 'Classification & metadata', 'Authorization & lifecycle', 'AI query'],
      features: [
        { title: 'OCR & full-text search', description: 'Documents become searchable text.' },
        { title: 'Metadata & taxonomy', description: 'Corporate classification.' },
        { title: 'RBAC', description: 'Role-based access control.' },
        { title: 'Lifecycle & WORM', description: 'Retention and disposal rules.' },
        { title: 'Audit trail', description: 'Traceable access and changes.' },
        { title: 'AI knowledge layer', description: 'Sourced enterprise Q&A.' },
      ],
      integrationSecurity: ['On-premise / air-gapped', 'LDAP / AD integration', 'Open API', 'Encryption and audit trail'],
      useCases: ['Large-scale document management', 'Centralized processing across distributed locations', 'Audited archives'],
      pocApproach: 'An archive PoC scoped to a selected document type.',
      faq: [
        { question: 'Can data be migrated?', answer: 'Yes, with a migration plan that has defined validation criteria.' },
        { question: 'Does it work on a closed network?', answer: 'Yes, fully on-premise scenarios are supported.' },
      ],
      relatedProducts: ['voodoo-rpa'],
      relatedSolutions: ['dijital-arsiv-ve-kurumsal-bilgi'],
    },
  },
  {
    slug: 'vultureeye',
    name: 'VultureEYE',
    category: 'Video Management System',
    icon: 'video',
    tagline: 'Centralized video management with a federated architecture and map-based operations.',
    showcase: true,
    problem: 'Scattered cameras produce context-less footage; operational visibility is low.',
    role: 'Unites locations and camera infrastructures into a federated operations layer.',
    proofs: ['Federated architecture', 'Map-based alarms', 'Open API and high availability'],
    sectors: ['Energy', 'Public Sector', 'City & Campus'],
    imageAlt: 'VultureEYE VMS map-based operations interface — product screen placeholder',
    detail: {
      problem: 'As camera count grows, visibility drops; alarms are context-less and locations are disconnected.',
      audience: ['Security operations centers', 'Critical facility managers', 'IT/infrastructure teams'],
      whyNow: 'Not more cameras, but more operational visibility is needed.',
      howItWorks: [
        'Different locations unite in a federated architecture.',
        'Alarms arrive with their location and footage on a map.',
        'Response is managed with an incident lifecycle and roles.',
      ],
      flow: ['Federation', 'Map-based alarm', 'Relevant footage', 'Incident lifecycle', 'Archive & export'],
      features: [
        { title: 'Federated architecture', description: 'Central control + local autonomy.' },
        { title: 'Map-based alarms', description: 'The alarm’s location on the map.' },
        { title: 'Incident lifecycle', description: 'Open, assign, close.' },
        { title: 'System health', description: 'Camera and infrastructure status.' },
        { title: 'Archive & export', description: 'Recording and evidence management.' },
        { title: 'Open API', description: 'Third-party integration.' },
      ],
      integrationSecurity: ['High availability', 'RBAC and audit trail', 'PSIM/SOC integration via open API'],
      useCases: ['Unified VMS in critical facilities', 'Multi-location security', 'Energy infrastructure visibility'],
      pocApproach: 'A federation and alarm-flow pilot across selected locations.',
      faq: [{ question: 'Can existing cameras be used?', answer: 'The federated architecture aims to unite different infrastructures.' }],
      relatedProducts: ['vision-qa'],
      relatedSolutions: ['video-yonetimi-ve-guvenlik-operasyonlari'],
    },
  },
  {
    slug: 'voodoo-rpa',
    name: 'VooDoo RPA',
    category: 'Robotic Process Automation',
    icon: 'workflow',
    tagline: 'Hand repetitive work to a digital workforce with a zero-code studio and unified console.',
    showcase: true,
    problem: 'Experts spend time on repetitive, rule-based work; errors and cost rise.',
    role: 'Automates rule-based processes with attended/unattended robots.',
    proofs: ['Zero-code studio', 'Attended & unattended robots', 'Unified console and REST API'],
    sectors: ['Finance', 'Public Sector', 'Manufacturing & Logistics'],
    imageAlt: 'VooDoo RPA studio and robot console — product screen placeholder',
    detail: {
      problem: 'Repetitive work grows error rates and cost linearly.',
      audience: ['Operations managers', 'Finance teams', 'Process excellence offices'],
      whyNow: 'With the right candidate process selected, automation delivers a fast return.',
      howItWorks: [
        'The candidate process is assessed for rules and volume.',
        'A low/zero-code robot is designed in the studio.',
        'Robots are managed and monitored from a unified console.',
      ],
      flow: ['Candidate analysis', 'Robot design', 'Test', 'Rollout', 'Console monitoring'],
      features: [
        { title: 'Zero-code studio', description: 'Visual flow design.' },
        { title: 'Attended & unattended', description: 'Desktop and server robots.' },
        { title: 'Unified console', description: 'Central scheduling and monitoring.' },
        { title: 'REST API', description: 'Programmatic integration.' },
        { title: 'Audit & log', description: 'Traceable steps.' },
      ],
      integrationSecurity: ['Application/web integration', 'Identity and authorization management', 'Audit trail'],
      useCases: ['Financial reconciliation', 'Cross-system data transfer', 'High-volume operation automation'],
      pocApproach: 'Selecting the first RPA candidate and demonstrating value with a measurable pilot.',
      faq: [{ question: 'Which process is suitable?', answer: 'Rule-based, repetitive, high-volume processes with digital inputs/outputs.' }],
      relatedProducts: ['dasbase'],
      relatedSolutions: ['akilli-surec-otomasyonu'],
    },
  },
  {
    slug: 'ebiokec',
    name: 'eBioKEC',
    category: 'Biometric Identity',
    icon: 'fingerprint',
    tagline: 'A secure access solution that verifies identity with cards, certificates and biometrics.',
    showcase: true,
    problem: 'Seeing identity is not enough; unverified transactions carry compliance risk.',
    role: 'Verifies identity with biometrics and a card, and ties approval to an audit trail.',
    proofs: ['Biometric verification', 'e-ID / NFC card reading', 'Audit trail'],
    sectors: ['Telecom', 'Finance', 'Healthcare'],
    imageAlt: 'eBioKEC biometric identity verification interface — product screen placeholder',
    detail: {
      problem: 'Fraud and unauthorized-access risks make verifying identity mandatory.',
      audience: ['Telecom/finance operations', 'Access management', 'Compliance teams'],
      whyNow: 'Verifying identity and tying approval to an audit trail is required for compliance.',
      howItWorks: [
        'Identity is verified with a card (NFC/e-ID) and biometrics.',
        'Approval is tied to an electronic signature and an audit trail.',
        'Access and time-and-attendance processes are secured.',
      ],
      flow: ['Identity capture', 'Card/NFC verification', 'Biometric verification', 'Approval', 'Audit trail'],
      features: [
        { title: 'Biometric verification', description: 'Biometrics such as fingerprint/face.' },
        { title: 'e-ID & NFC', description: 'Electronic ID-card reading.' },
        { title: 'Electronic signature binding', description: 'Approval with eBioSign.' },
        { title: 'T&A integration', description: 'Time-and-attendance control.' },
        { title: 'Audit trail', description: 'Traceable verification.' },
      ],
      integrationSecurity: ['Personal data protection', 'Integration with identity/access systems', 'Audit trail'],
      useCases: ['Identity verification in telecom', 'Digital consent in healthcare', 'Enterprise access'],
      pocApproach: 'A pilot validating the verification flow end-to-end on one channel.',
      faq: [{ question: 'Which cards are supported?', answer: 'e-ID and NFC-based ID cards are targeted; scope is finalized during the project.' }],
      relatedSolutions: ['dijital-kimlik-biyometri-ve-erisim', 'saglikta-dijital-donusum'],
    },
  },
  {
    slug: 'vision-qa',
    name: 'Vision QA',
    category: 'Computer Vision / Quality',
    icon: 'scan-eye',
    tagline: 'Vision intelligence that turns camera footage into counting, quality and anomaly decisions.',
    showcase: true,
    problem: 'Counting and quality control are manual and error-prone; cost rises as they scale.',
    role: 'Turns footage into an intelligent sensor that produces decisions.',
    proofs: ['Object detection', 'Quality verification', 'Edge AI'],
    sectors: ['Manufacturing & Logistics', 'Defense & Aerospace'],
    imageAlt: 'Vision QA image-based quality-control interface — product screen placeholder',
    detail: {
      problem: 'Manual counting/quality control is inconsistent and costly.',
      audience: ['Manufacturing/quality managers', 'Logistics operations', 'Facility security'],
      whyNow: 'Vision-based AI delivers consistent and measurable decisions.',
      howItWorks: [
        'Camera streams are processed at the edge or centrally.',
        'Object detection produces counting and quality decisions.',
        'Anomalies are relayed to operations.',
      ],
      flow: ['Image capture', 'Processing', 'Object detection', 'Decision', 'Notification'],
      features: [
        { title: 'Object detection', description: 'Real-time detection.' },
        { title: 'Quality verification', description: 'Image-based QA.' },
        { title: 'Counting (RPQ)', description: 'Automatic counting.' },
        { title: 'Edge AI', description: 'Low-latency processing.' },
        { title: 'Anomaly detection', description: 'Unexpected conditions.' },
      ],
      integrationSecurity: ['Existing camera infrastructure', 'VMS/business-system integration', 'Data privacy'],
      useCases: ['Quality control in manufacturing', 'Counting in logistics', 'Anomaly detection on premises'],
      pocApproach: 'A scoped computer-vision PoC with a measurable accuracy target.',
      faq: [{ question: 'How is PoC success measured?', answer: 'By accuracy against reference data and false positive/negative rates.' }],
      relatedProducts: ['vultureeye'],
      relatedSolutions: ['yapay-zeka-ve-goruntu-isleme'],
    },
  },
  {
    slug: 'ebiosign',
    name: 'eBioSign',
    category: 'Electronic Signature',
    icon: 'badge-check',
    tagline: 'Ties document approval to an audit trail with biometric and electronic signatures.',
    problem: 'Document approval is not traceable or verifiable.',
    role: 'Secures approval with electronic/biometric signatures and an audit trail.',
    proofs: ['Biometric signature', 'Audit trail', 'Document integrity'],
    sectors: ['Telecom', 'Finance', 'Healthcare'],
    imageAlt: 'eBioSign electronic signature interface — product screen placeholder',
    detail: {
      problem: 'Manual approval is untraceable and has weak legal grounding.',
      audience: ['Operations and legal', 'Compliance teams', 'Customer transactions'],
      whyNow: 'Electronic approval delivers speed and traceability.',
      howItWorks: ['The document is prepared.', 'A biometric/electronic signature is captured.', 'Integrity and an audit trail are bound.'],
      flow: ['Document', 'Signature', 'Integrity', 'Audit trail'],
      features: [
        { title: 'Biometric signature', description: 'Approval with biometrics.' },
        { title: 'Document integrity', description: 'Tamper-evidence assurance.' },
        { title: 'Audit trail', description: 'Traceable approval.' },
      ],
      integrationSecurity: ['Personal data protection', 'Document-system integration', 'Audit trail'],
      useCases: ['Electronic contracts', 'Digital consent', 'Enterprise approval flows'],
      pocApproach: 'A pilot validating one approval flow end-to-end.',
      faq: [{ question: 'How is legal validity ensured?', answer: 'Signature type and regulatory compliance are verified by authorities within the project scope.' }],
      relatedProducts: ['ebiokec'],
      relatedSolutions: ['dijital-kimlik-biyometri-ve-erisim'],
    },
  },
  {
    slug: 'kimo',
    name: 'KimO',
    category: 'Identity Verification',
    icon: 'fingerprint',
    tagline: 'A solution that ties identity reading and verification to enterprise processes.',
    problem: 'Identity reading is manual and disconnected from processes.',
    role: 'Reads and verifies identity and ties it to the business process.',
    proofs: ['Identity reading', 'Verification', 'Process integration'],
    sectors: ['Telecom', 'Public Sector'],
    imageAlt: 'KimO identity verification interface — product screen placeholder',
    detail: {
      problem: 'Identity reading stays isolated and disconnected from processes.',
      audience: ['Customer transactions', 'Branch/dealer operations', 'Compliance teams'],
      whyNow: 'Verified identity makes a transaction secure and auditable.',
      howItWorks: ['Identity is read.', 'It is verified.', 'It is tied to the business process.'],
      flow: ['Reading', 'Verification', 'Process binding'],
      features: [
        { title: 'Identity reading', description: 'Card and document reading.' },
        { title: 'Verification', description: 'Identity verification.' },
        { title: 'Integration', description: 'Binding to processes.' },
      ],
      integrationSecurity: ['Personal data protection', 'Process integration', 'Audit trail'],
      useCases: ['Branch identity verification', 'Dealer transactions', 'Public service points'],
      pocApproach: 'A pilot validating the verification flow at one transaction point.',
      faq: [{ question: 'Does it work with other products?', answer: 'An end-to-end identity-approval flow can be built together with eBioKEC and eBioSign.' }],
      relatedProducts: ['ebiokec', 'ebiosign'],
      relatedSolutions: ['dijital-kimlik-biyometri-ve-erisim'],
    },
  },
]

export const showcaseProductsEn = productsEn.filter((p) => p.showcase)

export const sectorsEn: Sector[] = [
  {
    slug: 'kamu',
    name: 'Public Sector',
    criticalProblem: 'Secure documents, identity and service continuity',
    solutionCombo: 'DASBase + Identity/KEC + Infrastructure',
    ctaLabel: 'Public-sector solution meeting',
    detail: {
      problem: 'In public services, documents, identity and service continuity require high security and auditability.',
      audience: ['Public IT managers', 'Institutional archive units', 'Service operations'],
      whyNow: 'Rising audit and service expectations make secure, continuous digital infrastructure mandatory.',
      howItWorks: [
        'Document and identity processes are managed with secure archiving and verification.',
        'Infrastructure and continuity architecture reduce service outages.',
      ],
      flow: ['Document/identity', 'Secure archive & verification', 'Infrastructure & continuity', 'Audit trail'],
      features: [
        { title: 'Secure archive', description: 'Auditable documents with DASBase.' },
        { title: 'Identity verification', description: 'Secure access with KEC.' },
        { title: 'Business continuity', description: 'Infrastructure and DR.' },
      ],
      integrationSecurity: ['On-premise / air-gapped', 'Enterprise identity integration', 'Audit trail'],
      useCases: ['Public document management', 'Identity at service points', 'Critical-infrastructure continuity'],
      pocApproach: 'A pilot for secure document and identity flow in one service process.',
      faq: [{ question: 'Does it work on a closed network?', answer: 'Yes, air-gapped networks are supported for public-sector scenarios.' }],
      relatedSolutions: ['dijital-arsiv-ve-kurumsal-bilgi', 'dijital-kimlik-biyometri-ve-erisim'],
    },
  },
  {
    slug: 'savunma-ve-havacilik',
    name: 'Defense & Aerospace',
    criticalProblem: 'Traceability, quality and facility security',
    solutionCombo: 'Vision QA + VultureEYE + Archive',
    ctaLabel: 'Field discovery',
    detail: {
      problem: 'Traceability, quality verification and facility security require the highest discipline.',
      audience: ['Quality and production', 'Facility security', 'Configuration management'],
      whyNow: 'Errors and security gaps can have critical consequences; traceability is mandatory.',
      howItWorks: ['Quality is verified with vision.', 'The facility is monitored with federated VMS.', 'Records are archived securely.'],
      flow: ['Quality verification', 'Facility monitoring', 'Secure archive', 'Traceability'],
      features: [
        { title: 'Vision QA', description: 'Quality verification.' },
        { title: 'VultureEYE', description: 'Facility security.' },
        { title: 'Archive', description: 'Traceable records.' },
      ],
      integrationSecurity: ['Air-gapped network', 'Strict access control', 'Audit trail'],
      useCases: ['Production quality traceability', 'Facility security', 'Configuration records'],
      pocApproach: 'A quality and traceability pilot on one line.',
      faq: [{ question: 'Is an air-gapped network possible?', answer: 'Yes, fully air-gapped scenarios are supported.' }],
      relatedProducts: ['vision-qa', 'vultureeye'],
    },
  },
  {
    slug: 'finans',
    name: 'Finance',
    criticalProblem: 'Secure access, operations automation and audit',
    solutionCombo: 'RPA + Archive + Biometrics + Security',
    ctaLabel: 'Opportunity analysis',
    detail: {
      problem: 'Intense operations, audit pressure and secure access must be managed at the same time.',
      audience: ['Operations', 'Compliance and audit', 'Information security'],
      whyNow: 'Manual operations and scattered access produce both cost and risk.',
      howItWorks: ['Repetitive work is automated with RPA.', 'Access is secured with biometrics.', 'Documents and auditing are managed with archiving.'],
      flow: ['Automation', 'Secure access', 'Archive & audit', 'Security monitoring'],
      features: [
        { title: 'VooDoo RPA', description: 'Operations automation.' },
        { title: 'Biometric access', description: 'Secure identity.' },
        { title: 'Archive & audit', description: 'Traceable records.' },
      ],
      integrationSecurity: ['Identity and access management', 'SIEM/EDR', 'Audit trail'],
      useCases: ['Reconciliation automation', 'Secure customer transactions', 'Audit and reporting'],
      pocApproach: 'An automation and audit pilot in one operational process.',
      faq: [{ question: 'Does it integrate with existing systems?', answer: 'It connects to existing systems through an open API and integration layer.' }],
      relatedProducts: ['voodoo-rpa', 'ebiokec'],
    },
  },
  {
    slug: 'saglik',
    name: 'Healthcare',
    criticalProblem: 'Digital consent, patient records and paperless processes',
    solutionCombo: 'e-ID + Archive + RPA + AI',
    ctaLabel: 'Transformation workshop',
    detail: {
      problem: 'Consent, patient records and processes still rely on paper and manual steps.',
      audience: ['Hospital management', 'Healthcare IT', 'Patient rights/compliance'],
      whyNow: 'A paperless hospital requires verified consent and accessible records.',
      howItWorks: ['Identity and consent are verified.', 'Records are managed in a digital archive.', 'Processes are automated.'],
      flow: ['Identity & consent', 'Digital record', 'Automation', 'Audit trail'],
      features: [
        { title: 'Digital consent', description: 'Consent with e-ID.' },
        { title: 'Patient record archive', description: 'Secure records.' },
        { title: 'Process automation', description: 'Paperless process with RPA.' },
      ],
      integrationSecurity: ['Health-data protection', 'HIS integration', 'Audit trail'],
      useCases: ['Digital consent', 'Paperless records', 'Process automation'],
      pocApproach: 'A consent and archive pilot in one clinical process.',
      faq: [{ question: 'What does paperless hospital mean?', answer: 'Beyond scanning; it means verifying consent, managing records and making the process auditable.' }],
      relatedProducts: ['ebiokec', 'dasbase'],
      relatedSolutions: ['saglikta-dijital-donusum'],
    },
  },
  {
    slug: 'enerji-ve-kritik-altyapi',
    name: 'Energy & Critical Infrastructure',
    criticalProblem: 'Distributed facility visibility and business continuity',
    solutionCombo: 'VultureEYE + Infrastructure + Cyber Security',
    ctaLabel: 'Architecture assessment',
    detail: {
      problem: 'Distributed facilities lack visibility and continuity; incident response is slow.',
      audience: ['Operations centers', 'IT/OT teams', 'Security management'],
      whyNow: 'Outages and security gaps in critical infrastructure are highly costly.',
      howItWorks: ['Facilities are monitored with federated VMS.', 'Infrastructure is designed for continuity.', 'Cyber security is integrated.'],
      flow: ['Facility monitoring', 'Continuity architecture', 'Cyber security', 'Central visibility'],
      features: [
        { title: 'VultureEYE', description: 'Distributed visibility.' },
        { title: 'Infrastructure & DR', description: 'Business continuity.' },
        { title: 'Cyber security', description: 'EDR/XDR/SIEM.' },
      ],
      integrationSecurity: ['OT/IT integration', 'High availability', 'Audit trail'],
      useCases: ['Distributed facility monitoring', 'Business continuity', 'Central security operations'],
      pocApproach: 'A visibility and continuity pilot across selected facilities.',
      faq: [{ question: 'Does it work with OT systems?', answer: 'The integration layer targets OT/IT convergence; scope is finalized in the project.' }],
      relatedProducts: ['vultureeye'],
      relatedSolutions: ['bt-altyapisi-ve-siber-guvenlik'],
    },
  },
  {
    slug: 'telekom',
    name: 'Telecom',
    criticalProblem: 'Identity verification and electronic contracts',
    solutionCombo: 'eBioKEC + eBioSign + KimO',
    ctaLabel: 'Technical fit meeting',
    detail: {
      problem: 'In subscriber acquisition, identity verification and electronic contracts require speed and compliance.',
      audience: ['Channel operations', 'Compliance', 'Customer experience'],
      whyNow: 'Manual processes, fraud risk and slow approval produce cost.',
      howItWorks: ['Identity is verified.', 'The contract is signed electronically.', 'The process is tied to an audit trail.'],
      flow: ['Identity', 'Verification', 'e-Contract', 'Audit trail'],
      features: [
        { title: 'eBioKEC', description: 'Identity verification.' },
        { title: 'eBioSign', description: 'Electronic contract.' },
        { title: 'KimO', description: 'Identity reading.' },
      ],
      integrationSecurity: ['Personal data protection', 'Channel-system integration', 'Audit trail'],
      useCases: ['Subscriber acquisition', 'Electronic contracts', 'Channel verification'],
      pocApproach: 'An identity-signature flow pilot on one channel.',
      faq: [{ question: 'Does it work at dealers?', answer: 'It is designed to work at channel and dealer points.' }],
      relatedProducts: ['ebiokec', 'ebiosign', 'kimo'],
    },
  },
  {
    slug: 'uretim-ve-lojistik',
    name: 'Manufacturing & Logistics',
    criticalProblem: 'Counting, quality, shipment and repetitive work',
    solutionCombo: 'RPQ + Vision QA + RPA',
    ctaLabel: 'PoC meeting',
    detail: {
      problem: 'Counting, quality and shipment are manual; errors and rework produce cost.',
      audience: ['Manufacturing/quality', 'Logistics', 'Operations'],
      whyNow: 'Vision intelligence and automation deliver consistency and speed.',
      howItWorks: ['Counting/quality is produced with vision.', 'Repetitive work is automated with RPA.'],
      flow: ['Vision counting/quality', 'Automation', 'Shipment verification', 'Reporting'],
      features: [
        { title: 'RPQ', description: 'Vision-based counting.' },
        { title: 'Vision QA', description: 'Quality verification.' },
        { title: 'VooDoo RPA', description: 'Process automation.' },
      ],
      integrationSecurity: ['ERP/WMS integration', 'Camera infrastructure', 'Audit trail'],
      useCases: ['Counting automation', 'Quality control', 'Shipment verification'],
      pocApproach: 'A counting/quality accuracy pilot on one line.',
      faq: [{ question: 'Does it integrate with existing ERP?', answer: 'ERP/WMS integration is targeted via open API.' }],
      relatedProducts: ['vision-qa', 'voodoo-rpa'],
    },
  },
  {
    slug: 'akilli-sehir-ve-kampus',
    name: 'Smart City & Campus',
    criticalProblem: 'Multi-location security and access',
    solutionCombo: 'VultureEYE + T&A + Biometrics',
    ctaLabel: 'Solution discovery',
    detail: {
      problem: 'Security and access management across multiple locations is scattered and hard to monitor.',
      audience: ['Campus/city management', 'Security operations', 'IT teams'],
      whyNow: 'A growing number of locations requires central visibility and access control.',
      howItWorks: ['Locations are monitored with federated VMS.', 'Access is managed with biometrics and T&A.'],
      flow: ['Location monitoring', 'Access management', 'Central visibility', 'Audit trail'],
      features: [
        { title: 'VultureEYE', description: 'Multi-location security.' },
        { title: 'T&A', description: 'Access and attendance.' },
        { title: 'Biometrics', description: 'Secure identity.' },
      ],
      integrationSecurity: ['Central identity', 'High availability', 'Audit trail'],
      useCases: ['Campus security', 'City locations', 'Access control'],
      pocApproach: 'A security and access pilot across selected locations.',
      faq: [{ question: 'How many locations does it scale to?', answer: 'The federated architecture aims to centrally manage a large number of locations.' }],
      relatedProducts: ['vultureeye'],
    },
  },
]

export const insightsEn: Insight[] = [
  {
    slug: 'daha-cok-kamera-neden-daha-cok-gorunurluk-degildir',
    title: 'Why more cameras is not more visibility',
    excerpt:
      'Camera count alone is not a measure of operational visibility. Context, alarm management and federation make the difference.',
    category: 'Security Operations',
    readingTime: '5 min',
    body: [
      'Adding cameras increases footage volume; but what determines how quickly an operator sees an incident and responds correctly is context.',
      'Context-less footage fatigues operators. Showing an alarm’s location on a map, automatically pulling the relevant footage and managing the incident lifecycle deliver real visibility.',
      'A federated architecture unites different locations and infrastructures into a single operations layer by balancing central control with local autonomy.',
    ],
  },
  {
    slug: 'tarama-yapmak-neden-dijital-donusum-degildir',
    title: 'Why scanning is not digital transformation',
    excerpt: 'Scanning documents is the first step; without managing, understanding and moving knowledge into processes, transformation is not complete.',
    category: 'Enterprise Knowledge',
    readingTime: '6 min',
    body: [
      'Scanning turns a document into a digital image; but without being searchable, classified and authorized, it is only a pile.',
      'With metadata, OCR, lifecycle and RBAC, a document settles into corporate memory.',
      'The AI layer ties knowledge to action with sourced queries.',
    ],
  },
  {
    slug: 'ilk-rpa-adayinizi-secmek-icin-10-soru',
    title: '10 questions to choose your first RPA candidate',
    excerpt: 'The right first process determines the return on automation. The questions to ask when evaluating a candidate.',
    category: 'Automation',
    readingTime: '7 min',
    body: [
      'A good first candidate is a rule-based, repetitive, high-volume process with digital inputs/outputs.',
      'The process’s exception rate, system dependencies and auditability should be assessed.',
      'Automation started without a measurable success criterion cannot prove its value.',
    ],
  },
  {
    slug: 'kimligi-gormek-ile-kimligi-dogrulamak-arasindaki-fark',
    title: 'The difference between seeing identity and verifying identity',
    excerpt: 'Seeing a document is not enough. Verification with a card, certificate and biometrics brings compliance and trust.',
    category: 'Digital Identity',
    readingTime: '5 min',
    body: [
      'Seeing identity is merely observing the presented document; it does not prevent fraud or unauthorized access.',
      'Verification proves the authenticity of identity with a card (NFC/e-ID), certificate and biometrics.',
      'Tying approval to an audit trail makes the transaction both secure and traceable.',
    ],
  },
  {
    slug: 'goruntu-tabanli-sayim-pocsinde-basari-nasil-olculur',
    title: 'How is success measured in an image-based counting PoC?',
    excerpt: 'In vision-intelligence PoCs, success is defined together by accuracy, error rate and operational impact.',
    category: 'Artificial Intelligence',
    readingTime: '6 min',
    body: [
      'Success starts with accuracy against a reference dataset.',
      'False positive and false negative rates determine the operational impact.',
      'A PoC must be defined from the start with scope, data, duration and KPIs.',
    ],
  },
  {
    slug: 'kagitsiz-hastane-gercekten-ne-demektir',
    title: 'What does a paperless hospital really mean?',
    excerpt: 'A paperless hospital is, beyond scanning, verified consent, accessible records and traceable processes.',
    category: 'Healthcare',
    readingTime: '6 min',
    body: [
      'Going paperless is not just scanning documents.',
      'Consent must be verified, patient records managed securely and the process made auditable.',
      'When identity verification, archiving and automation work together, a truly paperless process is built.',
    ],
  },
]

export const successStoriesEn: SuccessStory[] = [
  {
    slug: 'buyuk-olcekli-kurumsal-belge-yonetimi',
    title: 'Large-scale enterprise document management',
    sector: 'Public / Finance',
    problem: 'An archive of millions of pages was unsearchable and unauditable.',
    approach: 'A corporate memory was built with a central digital archive, OCR, metadata and RBAC.',
    scope: ['DASBase', 'OCR & metadata', 'RBAC & lifecycle'],
    outcome: 'The goal is to increase the speed and auditability of document access.',
    outcomeLabel: 'Beklenen iş etkisi',
  },
  {
    slug: 'dagitik-lokasyonlarda-merkezi-belge-isleme',
    title: 'Centralized document processing across distributed locations',
    sector: 'Public Sector',
    problem: 'Document processes ran disconnected across different locations.',
    approach: 'The document flow was unified in a central archive and workflow layer.',
    scope: ['DASBase', 'Workflow', 'Integration'],
    outcome: 'The goal is to achieve cross-location consistency and central auditability.',
    outcomeLabel: 'PoC hedefi',
  },
  {
    slug: 'yogun-operasyonlarda-robotik-surec-otomasyonu',
    title: 'Robotic process automation in high-volume operations',
    sector: 'Finance',
    problem: 'High-volume repetitive transactions were performed manually.',
    approach: 'Candidate processes were selected and handed to robots with VooDoo RPA.',
    scope: ['VooDoo RPA', 'Console monitoring', 'REST API'],
    outcome: 'A reduction in repetitive workload and an improvement in error rates are expected.',
    outcomeLabel: 'Beklenen iş etkisi',
  },
  {
    slug: 'kritik-tesislerde-birlesik-video-yonetimi',
    title: 'Unified video management in critical facilities',
    sector: 'Energy',
    problem: 'Camera infrastructures across distributed facilities could not be monitored centrally.',
    approach: 'Locations were unified in the VultureEYE federated architecture.',
    scope: ['VultureEYE', 'Federation', 'Map-based alarms'],
    outcome: 'The goal is to improve incident response time and central visibility.',
    outcomeLabel: 'PoC hedefi',
  },
]
